<!-- item will be appened to this layout -->
<!-- <div id="log" class="sl__chat__layout">
</div> -->

<!-- chat item -->
<!-- <script type="text/template" id="chatlist_item"> -->
  <div data-from="<?= $from ?>" data-id="<?= $messageId ?>">

      <div class="parent">
          <div class="box-logo">
              <img src="https://tyrolium.fr/Contenu/Image/Client/auroretvv.png" width="50px">
          </div>

          <div class="box-msg">
            <span class="meta" style="color: <?= $color ?>">

              <span class="badges">
              </span>

              <span class="name"><?= $from ?></span>

            </span>

            <span class="message">
              <?= $message ?>
            </span>
          </div>
      </div>

  </div>
<!-- </script> -->