<style>
@import url(https://fonts.googleapis.com/css?family=Roboto:700);

* {
    box-sizing: border-box;
}

html, body {
    height: 100%;
    overflow: hidden;
}

#log>div {
    animation: fadeInRight .3s ease forwards, fadeOut 0.5s ease <?= $message_hide_delay ?> forwards;
    -webkit-animation: fadeInRight .3s ease forwards, fadeOut 0.5s ease <?= $message_hide_delay ?> forwards;
}

.colon {
    display: none;
}

#log {
    display: table;
    position: absolute;
    bottom: 0;
    left: 0;
    padding: 0 10px 10px;
    width: 100%;
    table-layout: fixed;
}

#log>div {
    display: table-row;
}

#log>div.deleted {
    visibility: hidden;
}

#log .emote {
    background-repeat: no-repeat;
    background-position: center;
    background-size: contain;
    padding: 0.4em 0.2em;
    position: relative;
}

#log .emote img {
    display: inline-block;
    height: 1em;
    opacity: 0;
}

/* #log .message,#log .meta {
    vertical-align: top;
    display: table-cell;
    padding-bottom: 0.1em;
} */

/* #log .meta {
    width: 35%;
    text-align: right;
    padding-right: 0.5em;
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
} */

#log .message {
    word-wrap: break-word;
    width: 65%;
}

.badge {
    display: inline-block;
    margin-right: 0.2em;
    position: relative;
    height: 1em;
    vertical-align: middle;
    top: -0.1em;
}

/* ------- ma partie ------- */


.all {
    display: flex;
    align-items: center;
}

.box-msg {
    border-radius: 10px;
    background-color: rgb(233, 204, 209);
    margin: 20px;
    padding-left: 30px;
    padding-right: 30px;
    padding-top: 1px;
    padding-bottom: 1px;
}

.name {
    color: red;
    display: block;
}

.message {
    margin-top: 10px; 
    font-size: small;
    color: black;
}


</style>