<style>


/* ------- Css de base ------- */

@import url(https://fonts.googleapis.com/css?family=Roboto:700);
@import url(https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap);
* {
    box-sizing: border-box;
}

html, body {
    height: 100%;
    overflow: hidden;
}

#log>div {
    animation: fadeInRight .3s ease forwards, fadeOut 0.5s ease <?= $message_hide_delay ?> forwards;
    -webkit-animation: fadeInRight .3s ease forwards, fadeOut 0.5s ease <?= $message_hide_delay ?> forwards;
}

.colon {
    display: none;
}

#log {
    display: table;
    position: absolute;
    bottom: 0;
    left: 0;
    padding: 0 10px 10px;
    width: 100%;
    table-layout: fixed;
}

#log>div {
    display: table-row;
}

#log>div.deleted {
    visibility: hidden;
}

#log .emote {
    background-repeat: no-repeat;
    background-position: center;
    background-size: contain;
    padding: 0.4em 0.2em;
    position: relative;
}

#log .emote img {
    display: inline-block;
    height: 1em;
    opacity: 0;
}

#log .message,#log .meta {
    vertical-align: top;
    /* display: table-cell; */
    padding-bottom: 0.1em;
}

#log .meta {
    /* width: 35%; */
    /* text-align: right; */
    /* padding-right: 0.5em;  */
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
}

#log .message {
    word-wrap: break-word;
    width: 65%;
}

.badge {
    display: inline-block;
    margin-right: 0.2em;
    position: relative;
    height: 1em;
    vertical-align: middle;
    top: -0.1em;
}

/* ------- Css Rajouté ------- */


.all {
    display: flex;
    align-items: center;
}

.box-logo img{
    width: 100px;
    margin-right: -20px;
}

.box-msg {
    border-radius: 12px;
    background-color: #FFDEEC;
    margin: 20px;
    padding-left: 35px;
    padding-right: 35px;
    padding-top: 15px;
    padding-bottom: 15px;
    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25) inset;
    min-width: 800px;
    max-width: 1000px;
}

.name {
    color: red;
    display: block;
    font-family: 'Poppins';
    padding-bottom: 6px;
    font-size: 30px;
}

.message {
    margin-top: 10px;
    color: black;
    font-size: 25px;
    font-family: 'Poppins';
    font-weight: 400;
    word-wrap: break-word;
    
}


</style>